hikiku_system:
  fullname: HiKiku
  shorname: HiKiku

hikiku_widget:
  fullname: HiKiku Widget
  shortname: Widget

hikiku_board:
  fullname: HiKiku Board
  shortname: Board

hikiku_http_sink:
  fullname: HiKiku HTTP Sink
  shortname: HTTP Sink

hikiku_app:
  fullname: HiKiku App
  shortname: App