hikiku_system:
  fullname: Hikiku
  shorname: Hikiku

hikiku_widget:
  fullname: Hikiku
  shortname: Hikiku

hikiku_board:
  fullname: Hikiku Board
  shortname: Board

hikiku_http_source:
  fullname: Hikiku HTTP Source
  shortname: HTTP Source

hikiku_app:
  fullname: Hikiku App
  shortname: App